[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["asynchronous", "embedded", "no-std"]
description = "Minimal non-blocking I/O layer"
keywords = ["await", "futures", "I/O"]
license = "MIT OR Apache-2.0"
name = "nb"
repository = "https://github.com/japaric/nb"
version = "0.1.0"

[dependencies]
